name: qv_exp
version: 0.1.2
author: Vadim Tsushko <vadimtsushko@gmail.com>
description: Syntax check tool for QlikView expressions.
homepage: https://github.com/vadimtsushko/qv_exp
dependencies:
  args: any
  browser: any
  csv: any
  meta: any
  petitparser: any
dev_dependencies:
  unittest: any
